name: IA_ITM
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.29.0
  - ipython=8.20.0
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.2.0
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.1.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.10.12
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - anyio==4.2.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - defusedxml==0.7.1
      - fastjsonschema==2.19.1
      - fonttools==4.47.2
      - fqdn==1.5.1
      - haversine==2.8.1
      - idna==3.6
      - ipympl==0.9.3
      - ipython-genutils==0.2.0
      - ipywidgets==7.7.1
      - isoduration==20.11.0
      - jinja2==3.1.3
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.2
      - jupyter-server==2.12.5
      - jupyter-server-terminals==0.5.2
      - jupyterlab==4.0.12
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.2
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - markupsafe==2.1.4
      - matplotlib==3.8.2
      - mistune==3.0.2
      - nbclient==0.9.0
      - nbconvert==7.14.2
      - nbformat==5.9.2
      - notebook==7.0.7
      - notebook-shim==0.2.3
      - numpy==1.26.3
      - overrides==7.7.0
      - pandas==2.2.0
      - pandocfilters==1.5.1
      - pillow==10.2.0
      - prometheus-client==0.19.0
      - pyarrow==15.0.0
      - pycparser==2.21
      - pyparsing==3.1.1
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - referencing==0.33.0
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.17.1
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - seaborn==0.13.1
      - send2trash==1.8.2
      - sniffio==1.3.0
      - soupsieve==2.5
      - terminado==0.18.0
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tomli==2.0.1
      - types-python-dateutil==2.8.19.20240106
      - tzdata==2023.4
      - uri-template==1.3.0
      - urllib3==2.2.0
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - widgetsnbextension==3.6.6
